/**
 * src/lib/secrets/ids.ts
 *
 * Identifier generators for the secret layer.
 *
 * `generateSecretId()` — the EncryptedSecret primary key (a.k.a. `secretRef` /
 * `encRef`). It is generated by the application BEFORE encryption so it can be
 * bound into the AES-GCM AAD (envelope `secretRef`). Two deliberate properties:
 *   1. CSPRNG-backed, 128 bits of entropy → collision-free in practice.
 *   2. < 32 characters → it does NOT trip the audit-sanitize high-entropy
 *      redaction rule (`^[A-Za-z0-9_-]{32,}$`), so it stays loggable as `encRef`.
 *
 * `generateOnboardingReference()` — the public GrowOnboardingSession.reference.
 * CSPRNG, >=128-bit, URL-safe. NOT a secret and explicitly NOT the sole callback
 * auth (Grow origin-auth is a Phase 2 dependency). Provided here as foundation;
 * not wired into any runtime path in Phase 1.
 */

import { randomBytes } from "node:crypto";

/**
 * Generate a ~26-char, cuid-like handle from 128 bits of CSPRNG entropy.
 * Format: leading 'c' + 25 base36 chars. Deliberately under 32 chars.
 */
export function generateSecretId(): string {
  // 16 bytes = 128 bits of entropy, rendered as base36 and left-padded to a
  // fixed 25-char width. The value itself is fully random; padding only fixes
  // the string length (keeps it < 32 so it remains audit-loggable as encRef).
  const value = BigInt("0x" + randomBytes(16).toString("hex"));
  return "c" + value.toString(36).padStart(25, "0");
}

/**
 * Generate a public onboarding reference: 256 bits of CSPRNG entropy, base64url
 * (43 chars, no padding). Opaque, unguessable, URL-safe.
 */
export function generateOnboardingReference(): string {
  return randomBytes(32).toString("base64url");
}
